In [3]:
import numpy as np
lista = [1,2,3,4,5,6,7,8,9]

lista2 = np.array(lista)

print(type(lista))
print(type(lista2))
print(lista2)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [5]:
lista2.ndim
lista2.shape

(9,)

In [9]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz2 = np.array(matriz)

print(matriz2.ndim)
print(matriz2.shape)

2
(3, 3)


In [10]:
lista2[::3]

array([1, 4, 7])

In [11]:
matriz2[0::3]

array([[1, 2, 3]])

In [17]:
array= np.linspace(0,100, num=20)
print(array)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [20]:
print(lista2)
print(np.sum(lista2))
print(np.mean(lista2))
print(np.median(lista2))
print(np.std(lista2))
print(np.var(lista2))

[1 2 3 4 5 6 7 8 9]
45
5.0
5.0
2.581988897471611
6.666666666666667


In [22]:
print(matriz2)
print(np.sum(matriz2))
print(np.mean(matriz2))
print(np.median(matriz2))
print(np.std(matriz2))
print(np.var(matriz2))
print(matriz2.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
5.0
5.0
2.581988897471611
6.666666666666667
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [24]:
array = np.array([[1, 2], [3, 4], [5, 6]])
print(array.size)

6


In [29]:
array_reshaped= array.reshape(3,2)
print(array_reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
import numpy as np
# Crear una matriz aleatoria de 4x4
matriz = np.random.randint(1, 10, (4, 4))
print("Matriz aleatoria:\n", matriz)

# Encontrar el máximo y mínimo
print("\nMáximo de la matriz:", np.max(matriz))
print("Mínimo de la matriz:", np.min(matriz))

# Calcular la suma de la diagonal
suma_diagonal = np.trace(matriz)
print("\nSuma de la diagonal:", suma_diagonal)

# Normalizar los valores de la matriz (valores entre 0 y 1)
matriz_normalizada = (matriz - np.min(matriz)) / (np.max(matriz) - np.min(matriz))
print("Matriz normalizada:", matriz_normalizada)

Matriz aleatoria:
 [[8 7 4 9]
 [3 8 9 5]
 [6 6 3 8]
 [1 5 7 2]]

Máximo de la matriz: 9
Mínimo de la matriz: 1

Suma de la diagonal: 21
Matriz normalizada: [[0.875 0.75  0.375 1.   ]
 [0.25  0.875 1.    0.5  ]
 [0.625 0.625 0.25  0.875]
 [0.    0.5   0.75  0.125]]
